### ISSUE TITLE
Create logo design for project

### ISSUE THREAD

**Issue by derek-botany** [OpenContributionsProject/opensourcecontributionssite#1]
The open source contributions project is made to help encourage companies to support open source projects through finances, time, and effort. We want a logo that captures that essence.

Here are a few logos that other projects that have a similar mission for inspiration
![image](https://user-images.githubusercontent.com/77015356/208575371-e7dbd097-32c4-4227-93bd-32ee48373b47.png)
![image](https://user-images.githubusercontent.com/77015356/208575479-aec96b1a-8248-40ff-be40-a4323e5f8711.png)
![image](https://user-images.githubusercontent.com/77015356/208575789-0ff2dad7-14d0-4676-873d-7525682c72f3.png)
![image](https://user-images.githubusercontent.com/77015356/208575907-70365a78-997b-4279-a332-62f6341a15d6.png)

**Comment by blackgirlbytes** [comment]
I accidentally made this issue with my fake account lol
